In [1]:
import sys
import os 
sys.path.append(os.path.abspath(os.path.join(os.getcwd(), '..')))
from src.analysis.sensitivity import SensitivityAnalyzer
from omegaconf import OmegaConf

In [2]:
parameter_ranges = OmegaConf.load('../param_config.yaml')
dependent_parameter_names = ['Pc_des']
dependent_parameters = [{'parameter_name': 'Pc_des', 'function': lambda Pa_des : Pa_des - 20000, 'dependent_param': 'Pa_des'}]

SA = SensitivityAnalyzer(parameter_ranges, dependent_parameter_names=None, method='sobol', seed=42, N=1024 , calculate_second_order=True)

SA.generate_samples()
SA.rescale_samples()
samples = SA.apply_dependent_parameters(dependent_parameters)
samples

,Tfc,Pa_des,Sc,Phi_c_des,epsilon_gdl,tau,epsilon_mc,epsilon_c,e,Re,i0_c_ref,kappa_co,kappa_c,Pc_des
0,345.931298,268431.866782,2.632068,0.132128,0.624495,3.51943,0.324434,0.240591,5,0.000001,42.263443,31.825707,0.952710,248431.866782
1,350.820492,268431.866782,2.632068,0.132128,0.624495,3.51943,0.324434,0.240591,5,0.000001,42.263443,31.825707,0.952710,248431.866782
2,345.931298,201919.596742,2.632068,0.132128,0.624495,3.51943,0.324434,0.240591,5,0.000001,42.263443,31.825707,0.952710,181919.596742
3,345.931298,268431.866782,1.789658,0.132128,0.624495,3.51943,0.324434,0.240591,5,0.000001,42.263443,31.825707,0.952710,248431.866782
4,345.931298,268431.866782,2.632068,0.145910,0.624495,3.51943,0.324434,0.240591,5,0.000001,42.263443,31.825707,0.952710,248431.866782
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28667,340.898636,152452.823874,1.307282,0.283673,0.728948,1.93546,0.292262,0.227824,3,0.000005,56.300426,20.085051,2.250420,132452.823874
28668,340.898636,152452.823874,1.307282,0.283673,0.728948,1.93546,0.292262,0.227824,3,0.000002,20.832063,20.085051,2.250420,132452.823874
28669,340.898636,152452.823874,1.307282,0.283673,0.728948,1.93546,0.292262,0.227824,3,0.000002,56.300426,31.383792,2.250420,132452.823874
28670,340.898636,152452.823874,1.307282,0.283673,0.728948,1.93546,0.292262,0.227824,3,0.000002,56.300426,20.085051,0.862373,132452.823874
28671,340.898636,152452.823874,1.307282,0.283673,0.728948,1.93546,0.292262,0.227824,3,0.000002,56.300426,20.085051,2.250420,132452.823874

In [3]:
15060+510

15570

In [4]:
dejvis = samples[0:15000]
camila = samples[15570:21836]
nathaly = samples[21836:]

In [8]:
camila

,Tfc,Pa_des,Sc,Phi_c_des,epsilon_gdl,tau,epsilon_mc,epsilon_c,e,Re,i0_c_ref,kappa_co,kappa_c,Pc_des
15000,344.816848,184388.228173,2.228055,0.244742,0.641935,3.528215,0.196861,0.221686,4,0.000004,67.237252,15.401462,0.954141,164388.228173
15001,344.816848,184388.228173,2.228055,0.244742,0.641935,3.528215,0.209283,0.162884,4,0.000004,67.237252,15.401462,0.954141,164388.228173
15002,344.816848,184388.228173,2.228055,0.244742,0.641935,3.528215,0.209283,0.221686,3,0.000004,67.237252,15.401462,0.954141,164388.228173
15003,344.816848,184388.228173,2.228055,0.244742,0.641935,3.528215,0.209283,0.221686,4,0.000001,67.237252,15.401462,0.954141,164388.228173
15004,344.816848,184388.228173,2.228055,0.244742,0.641935,3.528215,0.209283,0.221686,4,0.000004,62.116789,15.401462,0.954141,164388.228173
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21831,355.382794,160337.531859,2.467720,0.455907,0.744422,1.312413,0.183778,0.178333,5,0.000002,59.312537,15.762654,1.069481,140337.531859
21832,355.382794,160337.531859,2.467720,0.455907,0.744422,1.757421,0.352689,0.178333,5,0.000002,59.312537,15.762654,1.069481,140337.531859
21833,355.382794,160337.531859,2.467720,0.455907,0.744422,1.757421,0.183778,0.239919,5,0.000002,59.312537,15.762654,1.069481,140337.531859
21834,355.382794,160337.531859,2.467720,0.455907,0.744422,1.757421,0.183778,0.178333,3,0.000002,59.312537,15.762654,1.069481,140337.531859
21835,355.382794,160337.531859,2.467720,0.455907,0.744422,1.757421,0.183778,0.178333,5,0.000003,59.312537,15.762654,1.069481,140337.531859

In [20]:
import pandas as pd
print(pd.__version__)

2.3.0

In [5]:
import pandas as pd

# Sample DataFrame
df = pd.DataFrame({'x':[10,20], 'y':[30,40]})

# Convert to dict list
print(df.to_dict(orient='records'))

[{'x': 10, 'y': 30}, {'x': 20, 'y': 40}]

In [6]:
from src.sampling.sampler import get_polarisation_curve_samples, build_fixed_parameters

In [ ]:
save_filepath = "../data/raw/sobol_sampling_final_camila3.pkl" #b 60+510
results = get_polarisation_curve_samples(sampled_parameters=camila.to_dict(orient='records'), fixed_parameters = build_fixed_parameters(), save_path=save_filepath, save_every=10)#

✅ Saved 10 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 20 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 30 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 40 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 50 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 60 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 70 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 80 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 90 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 100 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 110 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 120 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 130 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 140 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 150 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 160 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 170 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 180 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 190 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 200 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 210 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 220 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 230 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 240 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 250 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 260 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 270 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 280 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 290 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 300 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 310 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 320 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 330 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 340 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 350 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 360 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 370 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 380 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 390 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 400 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 410 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 420 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 430 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 440 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 450 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 460 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 470 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 480 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 490 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 500 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 510 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 520 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 530 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 540 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 550 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 560 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 570 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 580 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 590 samples to ../data/raw/sobol_sampling_final_camila3.pkl

d:\Users\kju10\Documents\LMU-STATISTICS & DATA SCIENCE MASTER\WS2425\Consulting\project\Sensitivity-Analysis-and-Surrogate-Modeling-of-PEM-Fuel-Cells\external\AlphaPEM\model\dif_eq.py:395: RuntimeWarning: invalid value encountered in scalar power
  dif_eq['deta_c / dt'] = 1 / (C_scl * Hcl) * ((i_fc + i_n) - i0_c_ref * (C_O2_ccl / C_O2ref) ** kappa_c *

❌ Sample 595 not valid: {'Tfc': 360.9477547059171, 'Pa_des': 206832.19876404293, 'Sc': 1.3552974983765371, 'Phi_c_des': 0.55204397819262, 'epsilon_gdl': 0.5613449258485345, 'tau': 2.585846909162402, 'epsilon_mc': 0.19329853203743697, 'epsilon_c': 0.2925861933008954, 'e': 5, 'Re': 1.7526703451351264e-06, 'i0_c_ref': 36.39079282401055, 'kappa_co': 33.81737006709446, 'kappa_c': 1.6144707797458397, 'Pc_des': 186832.19876404293}
   Error: array must not contain infs or NaNs
✅ Saved 600 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 610 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 620 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 630 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 640 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 650 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 660 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 670 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 680 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 690 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 700 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 710 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 720 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 730 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 740 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 750 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 760 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 770 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 780 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 790 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 800 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 810 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 820 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 830 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 840 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 850 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 860 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 870 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 880 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 890 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 900 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 910 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 920 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 930 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 940 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 950 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 960 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 970 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 980 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 990 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 1000 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 1010 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 1020 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 1030 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 1040 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 1050 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 1060 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 1070 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 1080 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 1090 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 1100 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 1110 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 1120 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 1130 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 1140 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 1150 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 1160 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 1170 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 1180 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 1190 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 1200 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 1210 samples to ../data/raw/sobol_sampling_final_camila3.pkl
❌ Sample 1217 not valid: {'Tfc': 349.15530672496186, 'Pa_des': 138035.72215053067, 'Sc': 1.2416523437598534, 'Phi_c_des': 0.6787206540088728, 'epsilon_gdl': 0.579170435954677, 'tau': 3.053405262857116, 'epsilon_mc': 0.3364505549464375, 'epsilon_c': 0.2777735834868439, 'e': 5, 'Re': 3.966785226567928e-06, 'i0_c_ref': 48.15655478195603, 'kappa_co': 38.451279928064906, 'kappa_c': 1.7171237765494736, 'Pc_des': 118035.72215053067}
   Error: array must not contain infs or NaNs
✅ Saved 1220 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 1230 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 1240 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 1250 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 1260 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 1270 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 1280 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 1290 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 1300 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 1310 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 1320 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 1330 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 1340 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 1350 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 1360 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 1370 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 1380 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 1390 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 1400 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 1410 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 1420 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 1430 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 1440 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 1450 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 1460 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 1470 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 1480 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 1490 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 1500 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 1510 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 1520 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 1530 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 1540 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 1550 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 1560 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 1570 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 1580 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 1590 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 1600 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 1610 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 1620 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 1630 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 1640 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 1650 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 1660 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 1670 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 1680 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 1690 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 1700 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 1710 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 1720 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 1730 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 1740 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 1750 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 1760 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 1770 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 1780 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 1790 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 1800 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 1810 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 1820 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 1830 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 1840 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 1850 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 1860 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 1870 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 1880 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 1890 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 1900 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 1910 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 1920 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 1930 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 1940 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 1950 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 1960 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 1970 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 1980 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 1990 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 2000 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 2010 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 2020 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 2030 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 2040 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 2050 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 2060 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 2070 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 2080 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 2090 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 2100 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 2110 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 2120 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 2130 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 2140 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 2150 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 2160 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 2170 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 2180 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 2190 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 2200 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 2210 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 2220 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 2230 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 2240 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 2250 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 2260 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 2270 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 2280 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 2290 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 2300 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 2310 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 2320 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 2330 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 2340 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 2350 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 2360 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 2370 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 2380 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 2390 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 2400 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 2410 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 2420 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 2430 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 2440 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 2450 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 2460 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 2470 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 2480 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 2490 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 2500 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 2510 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 2520 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 2530 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 2540 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 2550 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 2560 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 2570 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 2580 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 2590 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 2600 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 2610 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 2620 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 2630 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 2640 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 2650 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 2660 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 2670 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 2680 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 2690 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 2700 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 2710 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 2720 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 2730 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 2740 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 2750 samples to ../data/raw/sobol_sampling_final_camila3.pkl
✅ Saved 2760 samples to ../data/raw/sobol_sampling_final_camila3.pkl