In [94]:
import sys
import os 
sys.path.append(os.path.abspath(os.path.join(os.getcwd(), '..')))
from src.analysis.sensitivity import SensitivityAnalyzer
from omegaconf import OmegaConf

In [ ]:
parameter_ranges = OmegaConf.load('../param_config.yaml')
dependent_parameter_names = ['Pc_des']
dependent_parameters = [{'parameter_name': 'Pc_des', 'function': lambda Pa_des : Pa_des - 20000, 'dependent_param': 'Pa_des'}]

SA = SensitivityAnalyzer(parameter_ranges, dependent_parameter_names=None, method='sobol', seed=42, N=1024 , calculate_second_order=True)

SA.generate_samples()
SA.rescale_samples()
samples = SA.apply_dependent_parameters(dependent_parameters)
samples

,Tfc,Pa_des,Sc,Phi_c_des,epsilon_gdl,tau,epsilon_mc,epsilon_c,e,Re,i0_c_ref,kappa_co,kappa_c,Pc_des
0,345.931298,268431.866782,2.632068,0.132128,0.624495,3.51943,0.324434,0.240591,5,0.000001,42.263443,31.825707,0.952710,248431.866782
1,350.820492,268431.866782,2.632068,0.132128,0.624495,3.51943,0.324434,0.240591,5,0.000001,42.263443,31.825707,0.952710,248431.866782
2,345.931298,201919.596742,2.632068,0.132128,0.624495,3.51943,0.324434,0.240591,5,0.000001,42.263443,31.825707,0.952710,181919.596742
3,345.931298,268431.866782,1.789658,0.132128,0.624495,3.51943,0.324434,0.240591,5,0.000001,42.263443,31.825707,0.952710,248431.866782
4,345.931298,268431.866782,2.632068,0.145910,0.624495,3.51943,0.324434,0.240591,5,0.000001,42.263443,31.825707,0.952710,248431.866782
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28667,340.898636,152452.823874,1.307282,0.283673,0.728948,1.93546,0.292262,0.227824,3,0.000005,56.300426,20.085051,2.250420,132452.823874
28668,340.898636,152452.823874,1.307282,0.283673,0.728948,1.93546,0.292262,0.227824,3,0.000002,20.832063,20.085051,2.250420,132452.823874
28669,340.898636,152452.823874,1.307282,0.283673,0.728948,1.93546,0.292262,0.227824,3,0.000002,56.300426,31.383792,2.250420,132452.823874
28670,340.898636,152452.823874,1.307282,0.283673,0.728948,1.93546,0.292262,0.227824,3,0.000002,56.300426,20.085051,0.862373,132452.823874
28671,340.898636,152452.823874,1.307282,0.283673,0.728948,1.93546,0.292262,0.227824,3,0.000002,56.300426,20.085051,2.250420,132452.823874

In [32]:
dejvis = samples[0:15000]
camila = samples[15000:21836]
nathaly = samples[21836:]

In [97]:
import pandas as pd
import glob

# Locate all pickle files in the folder
file_paths = glob.glob('../sampling_test/*.pkl')

# Read each pickle file into a DataFrame and collect them
df_list = [pd.read_pickle(path) for path in file_paths]

# Concatenate all DataFrames vertically into one
combined_df = pd.concat(df_list, ignore_index=True)

# Print the overall shape
print(f"Combined DataFrame shape: {combined_df.shape}")

Combined DataFrame shape: (4000, 48)

In [114]:
import os
import pandas as pd

# Directory containing the pickle files
folder_path = '../sampling_test'

# List to collect individual DataFrames
df_list = []

# Iterate over all files in the directory
for filename in os.listdir(folder_path):
    if filename.endswith('.pkl'):
        file_path = os.path.join(folder_path, filename)
        df = pd.read_pickle(file_path)
        df_list.append(df)

# Concatenate all DataFrames vertically into one
combined_df = pd.concat(df_list, ignore_index=True)

# Display the combined DataFrame to the user

# Print the overall shape
print(f"Combined DataFrame shape: {combined_df.shape}")

Combined DataFrame shape: (4000, 48)

In [122]:
list(pd.read_csv('../sampling_test/results_sobol10.csv').columns)

['Unnamed: 0',
 'Tfc',
 'Pa_des',
 'Sc',
 'Phi_c_des',
 'epsilon_gdl',
 'tau',
 'epsilon_mc',
 'epsilon_c',
 'e',
 'Re',
 'i0_c_ref',
 'kappa_co',
 'kappa_c',
 'Pc_des',
 't_step',
 'i_step',
 'delta_pola',
 'i_EIS',
 'ratio_EIS',
 'f_EIS',
 't_EIS',
 'current_density',
 'max_step',
 'n_gdl',
 't_purge',
 'type_fuel_cell',
 'type_current',
 'type_auxiliary',
 'type_control',
 'type_purge',
 'type_display',
 'type_plot',
 'C_scl',
 'i_max_pola',
 'Aact',
 'Hgdl',
 'Hmem',
 'Hcl',
 'Hgc',
 'Wgc',
 'Lgc',
 'Sa',
 'Phi_a_des',
 'a_slim',
 'b_slim',
 'a_switch',
 'ifc_0',
 'ifc_1',
 'ifc_2',
 'ifc_3',
 'ifc_4',
 'ifc_5',
 'ifc_6',
 'ifc_7',
 'ifc_8',
 'ifc_9',
 'ifc_10',
 'ifc_11',
 'ifc_12',
 'ifc_13',
 'ifc_14',
 'ifc_15',
 'ifc_16',
 'ifc_17',
 'ifc_18',
 'ifc_19',
 'ifc_20',
 'ifc_21',
 'ifc_22',
 'ifc_23',
 'ifc_24',
 'ifc_25',
 'ifc_26',
 'ifc_27',
 'ifc_28',
 'ifc_29',
 'ifc_30',
 'Ucell_0',
 'Ucell_1',
 'Ucell_2',
 'Ucell_3',
 'Ucell_4',
 'Ucell_5',
 'Ucell_6',
 'Ucell_7',
 'Ucell_8',
 'Ucell_9',
 'Ucell_10',
 'Ucell_11',
 'Ucell_12',
 'Ucell_13',
 'Ucell_14',
 'Ucell_15',
 'Ucell_16',
 'Ucell_17',
 'Ucell_18',
 'Ucell_19',
 'Ucell_20',
 'Ucell_21',
 'Ucell_22',
 'Ucell_23',
 'Ucell_24',
 'Ucell_25',
 'Ucell_26',
 'Ucell_27',
 'Ucell_28',
 'Ucell_29',
 'Ucell_30']

In [145]:
pd.read_pickle('../sampling_test/results_sobol5000.pkl')

,Tfc,Pa_des,Sc,Phi_c_des,epsilon_gdl,tau,epsilon_mc,epsilon_c,e,Re,...,Hgc,Wgc,Lgc,Sa,Phi_a_des,a_slim,b_slim,a_switch,ifc,Ucell
0,334.334976,135696.165362,2.619854,0.615260,0.660912,1.678534,0.159581,0.269489,4,0.000002,...,0.0005,0.00045,9.67,1.3,0.5,0,1,0.99,"[0.0008116223645297851, 0.10081024709079815, 0...","[1.0610495136449654, 0.9878450302369526, 0.949..."
1,334.334976,135696.165362,2.619854,0.615260,0.660912,1.678534,0.159581,0.269489,4,0.000002,...,0.0005,0.00045,9.67,1.3,0.5,0,1,0.99,"[0.0008079561408327883, 0.10080657457561082, 0...","[1.0141065139866359, 0.9500698946686646, 0.913..."
2,334.334976,135696.165362,2.619854,0.615260,0.660912,1.678534,0.159581,0.269489,4,0.000002,...,0.0005,0.00045,9.67,1.3,0.5,0,1,0.99,"[0.0008062906865962227, 0.10080490624444223, 0...","[1.0542623312763242, 0.9800137176509124, 0.941..."
3,334.334976,135696.165362,2.619854,0.615260,0.660912,1.678534,0.159581,0.269489,4,0.000002,...,0.0005,0.00045,9.67,1.3,0.5,0,1,0.99,"[0.0008138054833104369, 0.1008124339290325, 0....","[1.0297947755575136, 0.9565925708603117, 0.918..."
4,346.240770,205626.762537,1.787271,0.257943,0.565434,1.365291,0.333960,0.273291,4,0.000002,...,0.0005,0.00045,9.67,1.3,0.5,0,1,0.99,"[0.0008153909826841389, 0.10081402211719069, 0...","[1.0945107930546072, 1.0215111081305794, 0.982..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,350.667618,297901.371647,1.651935,0.350144,0.579159,2.739054,0.217109,0.158222,4,0.000001,...,0.0005,0.00045,9.67,1.3,0.5,0,1,0.99,"[0.0008168271378123425, 0.10081546069882702, 0...","[0.88936514417776, 0.855035624674578, 0.829978..."
996,350.667618,297901.371647,1.651935,0.350144,0.579159,2.739054,0.217109,0.158222,4,0.000001,...,0.0005,0.00045,9.67,1.3,0.5,0,1,0.99,"[0.0008086484929055004, 0.10080726812017633, 0...","[0.9578459192561841, 0.920399175847533, 0.8938..."
997,350.667618,297901.371647,1.651935,0.350144,0.579159,2.739054,0.217109,0.158222,4,0.000001,...,0.0005,0.00045,9.67,1.3,0.5,0,1,0.99,"[0.0008167395191718942, 0.10081537293239175, 0...","[1.1272795712349575, 1.0909383334580791, 1.063..."
998,350.667618,148453.906191,2.585898,0.407714,0.756964,2.578013,0.280573,0.185792,5,0.000004,...,0.0005,0.00045,9.67,1.3,0.5,0,1,0.99,"[0.0008147705988949373, 0.10081340068256382, 0...","[1.0347757848007961, 0.9527077208619397, 0.904..."
999,334.478465,297901.371647,2.585898,0.407714,0.756964,2.578013,0.280573,0.185792,5,0.000004,...,0.0005,0.00045,9.67,1.3,0.5,0,1,0.99,"[0.0008219366467031254, 0.10082057877192496, 0...","[1.1511177465656364, 1.1058594638251222, 1.074..."